config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    # passwords: 'users/passwords'
    # ToDo: facebook認証に応じて追加
    # omniauth_callbacks: "users/omniauth_callbacks"
  }
  as :user do
    get 'users/sign_up/registration', to: 'users/registrations#new', as: :user_registration
    get 'users/sign_up', to: 'users/registrations#register', as: :register_user_registration
    post 'users/sign_up/sms_confirmation', to: 'users/registrations#validation', as: :user_validation
    get 'users/sign_up/sms_confirmation', to: 'users/registrations#sms_confirmation', as: :sms_confirmation_user_registration
    post 'users/sign_up/add_phone_number', to: 'users/registrations#add_phone_number', as: :add_phone_number
    get 'users/sign_up/sms_confirmation/sms', to: 'users/registrations#verification_code_input', as: :verification_code_input
    post 'users/sign_up/verification', to: 'users/registrations#verification', as: :verification
    get 'users/sign_up/address', to: 'users/registrations#address', as: :address_user_registration
    get 'users/sign_up/credit_card', to: 'users/registrations#credit_card', as: :credit_card_user_registration
    get 'users/sign_up/finish', to: 'users/registrations#finish', as: :finish_user_registration
    post 'users', to: 'users/registrations#create', as: :create_user_registration
    get 'users/:id', to: 'users#show', as: :show_user_plofile
    # get 'mypage/email_password', to: 'users/registrations#edit', as: :email_password_mypage_index
    # get 'mypage/email_password/confirmation', to: 'users/registrations#update_confirmation', as: :email_password_confirmation_mypage_index
    put 'mypage/email_password', to: 'users/registrations#update', as: :update_user_registration
  end

  root to: "items#index"
  resources :mypage, only: [:index] do
    collection do
      get "notification", "todo", "purchase", "purchased", "news", "support", "sales", "point", "profile", "email_password", "confirmation", "identification", "sms_confirmation", "help_center"
    end
  end

  as :mypage do
    post "identification", to: "mypage#create_identification"
    patch "identification", to: "mypage#create_identification"
    get "mypage/like/history", to: "mypage#like"
    get "mypage/listings/listing", to: "mypage#listing"
    get "mypage/listings/in_progress", to: "mypage#in_progress"
    get "mypage/listings/completed", to: "mypage#completed"
    get "mypage/review/history", to: "mypage#review"
    get "logout", to: "mypage#logout"
    patch "mypage/profile", to: "mypage#update_profile"
  end

  as :address do 
    get 'mypage/deliver_address', to: 'addresses#edit', as: :edit_address  
    post 'address', to: 'addresses#create', as: :create_address
    patch 'address', to: 'addresses#update', as: :update_address
  end
  
  as :items do
    get "transaction/done/:id", to: "items#done", as: :items_done
    get "transaction/buy/:id", to: "items#buy", as: :items_buy
    patch "transaction/pay/:id", to: "items#pay", as: :items_pay
    get "items/sell", to: "items#new", as: :items_sell
    get "items/search", to: "items#search"
  end
  
  resources :items, except: :new do
    collection do
      get "category_parent", defaults: {format:'json'} 
      get 'category_children', defaults: {format:'json'}
      get 'category_grandchildren', defaults: {format:'json'}
    end
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories,  only: [:index, :show] 
  resources :brands,  only: [:index, :show]
  resources :cards, only: [:new, :create, :destroy,]
  as :cards do
    get "mypage/card", to: "cards#card"
  end

  # 一番下に置いてください↓
  get '*path', controller: 'application', action: 'render_404'

end

app/views/shared/_address.html.haml
.single__field
  .single__field__label
    = label :address, :name, "お名前"
    %span.single__field__require 必須
  .single__field__input
    = f.text_field :first_name, autofocus: true, placeholder: "例) 山田"
  .single__field__input
    = f.text_field :last_name, placeholder: "例) 彩"
.single__field
  .single__field__label
    = label :address, :name_kana, "お名前カナ"
    %span.single__field__require 必須
  .single__field__input
    = f.text_field :first_name_kana, placeholder: "例) ヤマダ"
  .single__field__input
    = f.text_field :last_name_kana, placeholder: "例) アヤ"
.single__field
  .single__field__label
    = f.label :postal_code, "郵便番号"
    %span.single__field__require 必須
  .single__field__input
    = f.text_field :postal_code, placeholder: "例) 123-4567"
.single__field
  .single__field__label
    = f.label :prefecture, "都道府県"
    %span.single__field__require 必須
  .single__field__select
    = f.collection_select :prefecture, Prefecture.all, :name, :name, {prompt: "---"}
.single__field
  .single__field__label
    = f.label :municipalities, "市区町村"
    %span.single__field__require 必須
  .single__field__input
    = f.text_field :municipalities, placeholder: "例) 横浜市緑区"
.single__field
  .single__field__label
    = f.label :address, "番地"
    %span.single__field__require 必須
  .single__field__input
    = f.text_field :address, placeholder: "例) 青山1-1-1"
.single__field
  .single__field__label
    = f.label :building, "建物名"
    %span.single__field__require.single__field__require--option 任意
  .single__field__input
    = f.text_field :building, placeholder: "例) 柳ビル103"
.single__field
  .single__field__label
    = f.label :phone, "電話"
    %span.single__field__require.single__field__require--option 任意
  .single__field__input
    = f.text_field :phone, placeholder: "例) 09012345678"

app/views/shared/_brand-nav.html.haml
//ブランドナビゲーションバー
%ul.header-nav-brand-wrap
  %li.header-nav-brand-wrap__parent
    %h3.header-nav-brand-wrap__parent--heading
      = link_to '/' do
        %span Yohei Date
  %li.header-nav-brand-wrap__parent
    %h3.header-nav-brand-wrap__parent--heading
      = link_to '/' do
        %span Takahiro Terakado
  %li.header-nav-brand-wrap__parent
    %h3.header-nav-brand-wrap__parent--heading
      = link_to '/' do
        %span Miyuki Maura
  %li.header-nav-brand-wrap__parent
    %h3.header-nav-brand-wrap__parent--heading
      = link_to '/' do
        %span Chizuru Shinoda
  %li.header-nav-brand-wrap__parent
    %h3.header-nav-brand-wrap__parent--heading
      = link_to '/' do
        %span Taiki Kamaka

app/views/shared/_category-nav.html.haml
-# //ブランド多段階ナビゲーションバー
%ul.header-nav-parent-wrap#header-nav-parent
  - @parents.each do |parent|
    %li.header-nav-parent
      %h3.header-nav-parent__heading
        =link_to category_path(parent.id),class:'header-nav-parent__a' do
          = parent.name
      %ul.header-nav-child-wrap
        - parent.children.each do |child|
          %li.header-nav-child
            = link_to category_path(child.id) do
              = child.name
            %ul.header-nav-grand-child-wrap
              - child.children.each do |grandchild|
                %li.header-nav-grand-child
                  = link_to category_path(grandchild.id) do
                    = grandchild.name

app/views/shared/_footer-info.html.haml
:ruby
  footerlists = [{
    name: "会社概要"
  },{
    name: "採用情報"
  },{
    name: "プレスリリース"
  },{
    name: "公式ブログ"
  },{
    name: "メルカリロゴ利用ガイドライン"
  }]

  footerlists2 = [{
    name: "メルカリガイド"
  },{
    name: "らくらくメルカリ便"
  },{
    name: "ゆうゆうメルカリ便"
  },{
    name: "大型メルカリ便"
  },{
    name: "車体取引ガイド"
  },{
    name: "メルカリあんしん・あんぜん宣言！"
  },{
    name: "偽ブランド品撲滅への取り組み"
  },{
    name: "メルカリボックス"
  }]

  footerlists3 = [{
    name: "プライバシーポリシー"
  },{
    name: "メルカリ利用規約"
  },{
    name: "あんしんスマホサポート制度に関する利用特約"
  },{
    name: "コンプライアンスポリシー"
  }]

  footerlists4 = [{
    name: "個人データの安全管理に係る基本方針"
  },{
    name: "特定商取引に関する表記"
  },{
    name: "資金決済法に基づく表示"
  },{
    name: "法令遵守と犯罪抑止のために"
  }]

  footerlists5 = [{
    name: "日本"
  },{
    name: "United States"
  }]


%nav.info
  .footer__cell.footer__cell__mercari
    .footer__head 
      メルカリについて
      %ul.footer__lists
        -footerlists.each do |list|
          =link_to "/" do
            %p.footer__lists__list
              =list[:name]
      %ul.footer-social-links
        %li.footer-social-links--icon
          =link_to "/" do
            =fa_icon "twitter", class:"footer-social-links--icon"
        %li.footer-social-links--icon
          =link_to "/" do
            =fa_icon "facebook-square", class:"footer-social-links--icon"

  .footer__cell.footer__cell__child
    .footer__head
      ヘルプ＆ガイド
      %ul.footer__lists
        -footerlists2.each do |list|
          =link_to "/" do
            %p.footer__lists__list
              =list[:name]

  .footer__cell.footer__cell__width
    .footer__head
      プライバシーと利用規約
      .inner__footer__cell
        .inner__footer__cell__child
          %ul.footer__lists
            -footerlists3.each do |list|
              =link_to "/" do
                %p.footer__lists__list
                  =list[:name]
        .inner__footer__cell__child
          %ul.footer__lists
            -footerlists4.each do |list|
              =link_to "/" do
                %p.footer__lists__list
                  =list[:name]
              
  .footer__cell.footer__cell__short
    .footer__head
      国
      %ul.footer__lists
        -footerlists5.each do |list|
          =link_to "/" do
            %p.footer__lists__list
              =list[:name]
              
  .footer__bottom
    =link_to "/" do
      = image_tag 'mercari_logo_white.svg', alt: 'mercari'
    .footer__copyright
      %small.single__page__footer__copyright__index © 2019 Mercari

app/views/shared/_footer.html.haml
.footer
  .footer__banner
    .footer__banner__pc
      .footer__banner__pc__inner
        %h2 スマホで簡単フリマアプリ
        %p 今すぐ無料でダウンロード！
        .footer__banner__pc__inner__icons
          =image_tag "mercari_icon_white_bg.png", class: "footer__banner__pc__inner__icons__mercari"
          =image_tag "app-store.svg", class:"footer__banner__pc__inner__icons__svg"
          =image_tag "google-play.svg",class: "footer__banner__pc__inner__icons__svg"
      .footer__banner__pc__img
        =image_tag "footer_content_pc.png"

  .footer__global
    =render "/shared/footer-info"

app/views/shared/_header-nav.html.haml
//パンくずリスト
%nav.nav
  %ul.nav-lists
    %li.nav-lists__list
      = breadcrumbs separator: " &rsaquo; "

app/views/shared/_header.html.haml
//ヘッダー
%header.header
  .header-inner
    .header-top
      .header-top__img
        = link_to '/',class: 'header-logo-link' do
          = image_tag 'mercari_logo.png', alt: 'mercari', height: '36', width: '134', class: 'header-logo'
                
      = form_tag('/items/search',class:'header-form', method: :get) do
        %input.search{name: "keyword", placeholder: '何かお探しですか？', type: "text", value: "#{params[:keyword]}", class:'search-txt-field',id: "search-box" }/
        %button.search-icon{title: "検索", type: "submit",id: "search-icon"}
          =fa_icon 'search'

    .header-bottom
      .header-nav
        %ul.header-nav__left
          %li#header-category
            %h2
              = link_to categories_path, class:'header-nav__left__category' do
                = fa_icon 'list',class:'header-nav__left__icon'
                %span.header-nav__left__category__span カテゴリーから探す
            = render '/shared/category-nav'

          %li#header-brand
            %h2
              = link_to '/',class:'header-nav__left__brand' do
                =fa_icon 'tag',class:'header-nav__left__icon'
                %span.b-left__span スタッフロール
              = render '/shared/brand-nav'
              
        .header-nav__right
          %ul.header-nav
            - if user_signed_in?
              %li.header-nav__user
                %h2
                  = link_to mypage_like_history_path, class:'header-nav__user__link' do
                    = fa_icon 'heart-o',class:'header-user-icon'
                    %span いいね！一覧
              %li.header-nav__user
                %h2
                  = link_to '/', class:'header-nav__user__link' do
                    = fa_icon 'bell-o',class:'header-user-icon'
                    %span お知らせ
              %li.header-nav__user
                %h2
                  = link_to '/',class:'header-nav__user__link' do
                    = fa_icon 'check',class:'header-user-icon'
                    %span やることリスト
              %li.header-nav__user.header-nav__user--mypage
                %h2
                  = link_to mypage_index_path,class:'header-nav__user__link' do
                    = image_tag 'mercari_icon.png',size:'32x32',class:'header-user-img'
                    %span マイページ

                  = render '/shared/header_mypage'

            - else
              %ul.header-user-list
                %li.header-user-list__new
                  =link_to '新規会員登録',register_user_registration_path
                %li.header-user-list__login
                  =link_to 'ログイン',new_user_session_path
%header.sp-header  
  .sp-header-inner#sp-header-inner
    .sp-header-top
      .sp-header-top__wrapper
        .sp-header-top__wrapper__img
          = link_to '/',class: 'sp-header-logo-link' do
            = image_tag 'mercari_logo.png', alt: 'mercari', height: '36', width: '134', class: 'header-logo'
        %ul.sp-header-nav
          - if user_signed_in?
            %li.sp-header-nav__user
              %h2
                = link_to '/', class:'sp-header-nav__user__link' do
                  = fa_icon 'bell-o',class:'sp-header-user-icon'
            %li.sp-header-nav__user
              %h2
                = link_to '/',class:'sp-header-nav__user__link' do
                  = fa_icon 'check',class:'sp-header-user-icon'
            %li.sp-header-nav__user
              %h2
                = link_to mypage_index_path,class:'sp-header-nav__user__link' do
                  = image_tag 'mercari_icon.png',size:'32x32',class:'sp-header-user-img'
            
          - else
            %ul.sp-header-user-list
              %li.sp-header-user-list__new
                =link_to '新規会員登録',register_user_registration_path
              %li.sp-header-user-list__login
                =link_to 'ログイン',new_user_session_path

    .sp-header-middle
      = form_tag('/items/search',class:'header-form', method: :get) do
        %input.search{name: "keyword", placeholder: '何かお探しですか？', type: "text", value: "", class:'search-txt-field' }/
        %button.search-icon{title: "検索", type: "submit"}
          =fa_icon 'search'

    .sp-header-bottom
      %ul.sp-header-bottom-box
        %li.sp-header-bottom-box__nav
          %h2
            = link_to categories_path do
              = fa_icon 'list',class:'sp-header-bottom-box__nav__icon'
              %span.sp-header-bottom-box__nav__span カテゴリーから探す
          = render '/shared/category-nav'

        %li.sp-header-bottom-box__nav
          %h2
            = link_to '/' do
              =fa_icon 'tag',class:'sp-header-bottom-box__nav__icon'
              %span.sp-header-bottom-box__nav__span スタッフロール 
            = render '/shared/brand-nav'

- unless current_page?(root_path)
  = render "/shared/header-nav"

app/views/shared/_header_mypage.html.haml
:ruby
  mypageheaderlists = [{
      name: "いいね！一覧",
      url: mypage_like_history_path
    },{
      name: "出品した商品-出品中",
      url: mypage_listings_listing_path
    },{
      name: "出品した商品-取引中",
      url: mypage_listings_in_progress_path
    },{
      name: "出品した商品-売却済み",
      url: mypage_listings_completed_path
    },{
      name: "購入した商品-取引中",
      url: purchase_mypage_index_path
  }]

.mypage__nav
  .mypage__nav__image
    .mypage__nav__icon
      %figure
        = image_tag current_user.image.url, size: "60x60"
      %h2.mypage__nav__icon__name
        = current_user.nickname

    .mypage__nav__review
      = link_to mypage_index_path, class: "header-mypage-number" do
        .mypage__nav__review__rate
          評価:
          %span.bold
            0
      = link_to mypage_listings_listing_path, class: "header-mypage-number" do
        .mypage__nav__review__display
          出品数:
          %span.bold
            = current_user.selling_items.count + current_user.sold_items.count


    .mypage__nav__number
      .mypage__nav__number__list
        = link_to mypage_index_path, class: "header-mypage-number" do
          .mypage__nav__number__box
            .mypage__nav__number__box__title
              売上金
            .mypage__nav__number__box__sales
              ¥ 0
            .mypage__nav__number__box__icon
              =fa_icon "angle-right", class: 'icon-chek'
        = link_to mypage_index_path, class: "header-mypage-number" do
          .mypage__nav__number__box
            .mypage__nav__number__box__title
              ポイント
            .mypage__nav__number__box__point
              P 0
            .mypage__nav__number__box__icon
              =fa_icon "angle-right", class: 'icon-chek'

      .mypage__nav--while

      .mypage__side
        .sidebar
          %ul.sidebar__lists
            -mypageheaderlists.each do |list|
              =link_to list[:url] do
                %li.sidebar__lists__list
                  %p 
                    =list[:name]
                  =fa_icon "angle-right"

app/views/shared/_search-side.html.haml
.sidebar
  =search_form_for(@keyword, url: items_search_path) do |f|  
    .search-side__sorts 
      = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} )
    
    .search-side     
      %h3.search-side__title
        詳細検索
      
      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "plus"
            = f.label :name_cont_all, "キーワードを追加する"
          .single__field__input     
            = f.search_field :name_cont_all, placeholder: "商品名", id: "search-item-name"

      .search-side__group
        .single__field.single__field--large.category-select-box
          .single__field__label
            .search-side__group__icon
              = fa_icon "list"
            = label :size, "カテゴリー"
          .single__field__select
            = f.collection_select :name, @parents, :id,:name,{prompt: "---"}, id: "search-parent-form"

        -#  ここでカテゴリーidのvalueを取得
        .single__field__input     
          = f.search_field :category_id_eq_any, id: "category-search", value: "", type: "hidden"

      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "expand"
            = label :size, "サイズ"
          .single__field__select
            = f.select :size_eq_any,[["---",""],["XXS以下","XXS以下"],["XS(SS)", "XS(SS)"],["S", "S"],["M","M"],["L","L"],["XL(LL)","XL(LL)"],["FREE SIZE","FREE SIZE"]], class: "single__field__select"            

      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "database"
            = f.label :price_gteq, "価格"
          .single__field__select
            %select#search-price
              %option(value="" ) ---
              %option(value="300,1000") 
                300 ~ 1000
              %option(value="1000,5000") 
                1000 ~ 5000
              %option(value="5000,10000") 
                5000 ~ 10000
              %option(value="10000,30000") 
                10000 ~ 30000
              %option(value="30000,50000") 
                30000 ~ 50000
              %option(value="50000") 
                50000 ~                 
          .search-side__group__price
            .single__field__input
              = f.search_field :price_gteq, placeholder: "¥ min", id: "search-price-min"
            %span.single__field__input ~
            .single__field__input
              = f.search_field :price_lteq, placeholder: "¥ max", id: "search-price-max"

      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "star"
            = f.label "商品の状態"
          .search-side__group__cheak
            .search-side__group__cheak__box
              = f.label "新品/未使用" do
                = f.check_box :condition_eq_any, { multiple: true }, "新品/未使用", ""
                %span 新品/未使用
            .search-side__group__cheak__box
              = f.label "未使用に近い" do
                = f.check_box :condition_eq_any, { multiple: true }, "未使用に近い", ""
                %span 未使用に近い
            .search-side__group__cheak__box
              = f.label "目立った傷や汚れなし" do
                = f.check_box :condition_eq_any, { multiple: true }, "目立った傷や汚れなし", ""
                %span 目立った傷や汚れなし
            .search-side__group__cheak__box
              = f.label "やや傷や汚れあり" do
                = f.check_box :condition_eq_any, { multiple: true }, "やや傷や汚れあり", ""
                %span やや傷や汚れあり
            .search-side__group__cheak__box
              = f.label "傷や汚れあり" do
                = f.check_box :condition_eq_any, { multiple: true }, "傷や汚れあり", ""
                %span 傷や汚れあり
            .search-side__group__cheak__box
              = f.label "全体的に状態が悪い" do
                = f.check_box :condition_eq_any, { multiple: true }, "全体的に状態が悪い", ""
                %span 全体的に状態が悪い

      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "truck"
            = f.label "配送料の負担"
          .search-side__group__cheak
            .search-side__group__cheak__box
              = f.label "着払い(購入者負担)" do
                = f.check_box :shipping_fee_eq_any, { multiple: true }, "着払い", ""
                %span 着払い(購入者負担)
            .search-side__group__cheak__box
              = f.label "着払い(購入者負担)" do
                = f.check_box :shipping_fee_eq_any, { multiple: true }, "送料込み", ""
                %span 送料負担(出品者負担)

      .search-side__group
        .single__field.single__field--large
          .single__field__label
            .search-side__group__icon
              = fa_icon "shopping-cart"
            = f.label "販売状況"
          .search-side__group__cheak#search-status-box
            .search-side__group__cheak__box
              = f.label "販売中" do
                = f.check_box :status_eq_any, { multiple: true }, 0, ""
                %span 販売中
            .search-side__group__cheak__box
              = f.label "売り切れ" do
                = f.check_box :status_eq_any, { multiple: true }, 1, ""
                %span 売り切れ

      .search-side__group
        = f.submit "検索する", class: "single__form__send-btn"

app/views/shared/_sell-btn.html.haml
=link_to items_sell_path, class: "footer-sell-btn" do
  .footer-sell-btn__word 出品
  =fa_icon "camera"       

app/views/shared/_sidebar.html.haml
:ruby 
  sidelists = [{
      name: "マイページ",
      url: mypage_index_path
    },{
      name: "お知らせ",
      url: notification_mypage_index_path
    },{
      name: "やることリスト",
      url: todo_mypage_index_path
    },{
      name: "いいね！一覧",
      url: mypage_like_history_path
    },{
      name: "出品する",
      url: items_sell_path
    },{
      name: "出品した商品-出品中",
      url: mypage_listings_listing_path
    },{
      name: "出品した商品-取引中",
      url:  mypage_listings_in_progress_path
    },{
      name: "出品した商品-売却済",
      url: mypage_listings_completed_path
    },{
      name: "購入した商品-取引中",
      url: purchase_mypage_index_path
    },{
      name: "購入した商品-過去の取引",
      url: purchased_mypage_index_path
    }]
    # ,{
    #   name: "ニュース一覧",
    #   url: news_mypage_index_path
    # },{
    #   name: "評価一覧",
    #   url:  mypage_review_history_path
    # },{
    #   name: "ガイド",
    #   url: help_center_mypage_index_path
    # },{
    #   name: "お問い合わせ",
    #   url: support_mypage_index_path
    # }
    

  # sidelists2 = [{
  #     name: "売上・振込申請",
  #     url: sales_mypage_index_path
  #   },{
  #     name: "ポイント",
  #     url: point_mypage_index_path
  #   }]

  sidelists3 = [{
      name: "プロフィール",
      url: profile_mypage_index_path
    },{
      name: "発送元・お届け先住所変更",
      url: edit_address_path
    },{
      name: "支払い方法",
      url: mypage_card_path
    },{
      name: "メール/パスワード",
      url: email_password_mypage_index_path
    },{
      name: "本人情報",
      url: identification_mypage_index_path
    },{
      name: "電話番号の確認",
      url: sms_confirmation_mypage_index_path
    },{
      name: "ログアウト",
      url: logout_path
    }]


.sidebar
  %ul.sidebar__lists
    -sidelists.each do |list|
      =link_to list[:url] do
        %li.sidebar__lists__list
          %p 
            =list[:name]
          =fa_icon "angle-right"
  -# %h3.sidebar__head
  -#   メルペイ
  -# %ul.sidebar__lists
  -#   -sidelists2.each do |list|
  -#     =link_to list[:url] do
  -#       %li.sidebar__lists__list
  -#         %p 
  -#           =list[:name]
  -#         =fa_icon "angle-right"
  %h3.sidebar__head
    設定
  %ul.sidebar__lists
    -sidelists3.each do |list|
      =link_to list[:url] do
        %li.sidebar__lists__list
          %p 
            =list[:name]
          =fa_icon "angle-right"

app/views/shared/_single-footer.html.haml
%footer.single__page__footer
  %nav
    = link_to "プライバシーポリシー", "/"
    = link_to "メルカリ利用規約", "/"
    = link_to "特定商取引に関する表記", "/"
  = link_to "/", class: "single__page__footer__logo" do
    = image_tag "logo-gray.svg", size: "100x50", alt: "mercari-gray"
  %p
    %small.single__page__footer__copyright © 2019 Mercari

app/views/shared/_single-header.html.haml
:ruby
  steps = ["会員情報", "電話番号認証", "お届け先住所入力", "支払い方法", "完了"]

%header.single__page__header
  = link_to "/" do
    = image_tag "mercari_logo.png", size: "185x50", alt: "mercari"
  - if controller_name == 'registrations' && action_name != 'register'
    %nav.sign-up__bar
      %ol.sign-up__bar__menus
        - steps.each_with_index do |step, i|
          - if i < @step_num
            %li
              = step
              .progress-status.progress-status--active
          - elsif i == @step_num
            %li.active-single-nav
              = step
              .progress-status.progress-status--active
          - else
            %li
              = step
              .progress-status 
    -# %nav.sign-up__bar
    -#   %ol.sign-up__bar__menus
    -#     %li.active-single-nav
    -#       会員情報
    -#       .progress-status.progress-status--active
    -#     %li
    -#       電話番号認証
    -#       .progress-status
    -#     %li
    -#       お届け先住所入力
    -#       .progress-status
    -#     %li
    -#       支払い方法
    -#       .progress-status
    -#     %li
    -#       完了
    -#       .progress-status