config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    # passwords: 'users/passwords'
    # ToDo: facebook認証に応じて追加
    # omniauth_callbacks: "users/omniauth_callbacks"
  }
  as :user do
    get 'users/sign_up/registration', to: 'users/registrations#new', as: :user_registration
    get 'users/sign_up', to: 'users/registrations#register', as: :register_user_registration
    post 'users/sign_up/sms_confirmation', to: 'users/registrations#validation', as: :user_validation
    get 'users/sign_up/sms_confirmation', to: 'users/registrations#sms_confirmation', as: :sms_confirmation_user_registration
    post 'users/sign_up/add_phone_number', to: 'users/registrations#add_phone_number', as: :add_phone_number
    get 'users/sign_up/sms_confirmation/sms', to: 'users/registrations#verification_code_input', as: :verification_code_input
    post 'users/sign_up/verification', to: 'users/registrations#verification', as: :verification
    get 'users/sign_up/address', to: 'users/registrations#address', as: :address_user_registration
    get 'users/sign_up/credit_card', to: 'users/registrations#credit_card', as: :credit_card_user_registration
    get 'users/sign_up/finish', to: 'users/registrations#finish', as: :finish_user_registration
    post 'users', to: 'users/registrations#create', as: :create_user_registration
    get 'users/:id', to: 'users#show', as: :show_user_plofile
    # get 'mypage/email_password', to: 'users/registrations#edit', as: :email_password_mypage_index
    # get 'mypage/email_password/confirmation', to: 'users/registrations#update_confirmation', as: :email_password_confirmation_mypage_index
    put 'mypage/email_password', to: 'users/registrations#update', as: :update_user_registration
  end

  root to: "items#index"
  resources :mypage, only: [:index] do
    collection do
      get "notification", "todo", "purchase", "purchased", "news", "support", "sales", "point", "profile", "email_password", "confirmation", "identification", "sms_confirmation", "help_center"
    end
  end

  as :mypage do
    post "identification", to: "mypage#create_identification"
    patch "identification", to: "mypage#create_identification"
    get "mypage/like/history", to: "mypage#like"
    get "mypage/listings/listing", to: "mypage#listing"
    get "mypage/listings/in_progress", to: "mypage#in_progress"
    get "mypage/listings/completed", to: "mypage#completed"
    get "mypage/review/history", to: "mypage#review"
    get "logout", to: "mypage#logout"
    patch "mypage/profile", to: "mypage#update_profile"
  end

  as :address do 
    get 'mypage/deliver_address', to: 'addresses#edit', as: :edit_address  
    post 'address', to: 'addresses#create', as: :create_address
    patch 'address', to: 'addresses#update', as: :update_address
  end
  
  as :items do
    get "transaction/done/:id", to: "items#done", as: :items_done
    get "transaction/buy/:id", to: "items#buy", as: :items_buy
    patch "transaction/pay/:id", to: "items#pay", as: :items_pay
    get "items/sell", to: "items#new", as: :items_sell
    get "items/search", to: "items#search"
  end
  
  resources :items, except: :new do
    collection do
      get "category_parent", defaults: {format:'json'} 
      get 'category_children', defaults: {format:'json'}
      get 'category_grandchildren', defaults: {format:'json'}
    end
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories,  only: [:index, :show] 
  resources :brands,  only: [:index, :show]
  resources :cards, only: [:new, :create, :destroy,]
  as :cards do
    get "mypage/card", to: "cards#card"
  end

  # 一番下に置いてください↓
  get '*path', controller: 'application', action: 'render_404'

end

app/models/item.rb
class Item < ApplicationRecord
  before_save :item_profit
  attr_accessor :image_validation, :image_files, :delete_image_files, :parent_id, :child_id

  validates :name, :description, :price, :size, :condition, :shipping_fee, :shipping_method, :prefecture, :shipping_date, presence: true
  # validates :image_validation if 
  
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :images
  # belongs_to_active_hash :category
  # belongs_to_active_hash :brand

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def item_profit
    self.profit = price * 0.9
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :user_signed_in?, only:[:new, :create, :edit, :update, :destroy]
  before_action :set_item, only:[:show, :edit, :update, :destroy, :buy, :pay]
  before_action :authenticate, only:[:new, :edit, :done, :buy]

  def index
    @items = Item.includes(:images).order("created_at desc").limit(8)
    ids = Category.find(1).descendant_ids
    @ladies_items = Item.where(category_id: ids).order("created_at desc").limit(4)
    ids = Category.find(2).descendant_ids
    @mens_items = Item.where(category_id: ids).order("created_at desc").limit(4)
    ids = Category.find(3).descendant_ids
    @babys_items = Item.where(category_id: ids).order("created_at desc").limit(4)
    ids = Category.find(7).descendant_ids
    @cosmetics_items = Item.where(category_id: ids).order("created_at desc").limit(4)
  end

  def show
    @comments = Comment.where(item_id: @item.id)
    @comment = Comment.new
    # @items = Item.where(params[:id])
   
    @user_items = Item.where(seller_id: @item.seller_id).where.not(id: @item.id).order('created_at DESC').limit(6)
  end

  def new
    @item = Item.new
    render layout: "single"
  end

  # 出品ページでカテゴリーのセレクトボックス用。jbuilderとroutes.rbと繋がっています
  def category_parent
    @select_parent = Category.find(params[:parent_id])
  end

  def category_children 
    @select_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @select_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    respond_to do |format|
      @item = Item.new(item_params)
      if @item.save
        item_params[:image_files].each do |image|
          @item.images.create(image: image)
        end
        format.html { redirect_to item_path(@item) }
        format.json
      else
        render :new, layout: "single"
      end
    end
  end
  
  def edit
    render layout: "single"
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        
        item_params[:delete_image_files]&.each do |image_num|
          @item.images[image_num.to_i].delete
        end

        item_params[:image_files]&.each do |image|
          @item.images.create(image: image)
        end
        
        format.html { redirect_to item_path(@item) }
        format.json { render json: { redirect: item_path(@item) } }

      else
        render :new, layout: "single"
      end
    end
  end

  def destroy
    if @item.destroy
      redirect_to action: "index"
    else
      flash[:notice] = "削除に失敗しました"
      redirect_to action: "show"
    end
  end

  def buy
    card = Card.find_by(user_id: current_user.id)
    if card
      Payjp.api_key = ENV["PAYJP_TEST_SECRET"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card = customer.cards.retrieve(card.card_id) 
    end
    render layout: "single"
  end

  def pay
    @item.update(pay_params)
    if @item.save  
      Payjp.api_key = ENV['PAYJP_TEST_SECRET']
      Payjp::Charge.create(
        amount: @item.price, # 決済する値段
        customer: current_user.card.customer_id,
        currency: 'jpy'
      )
      redirect_to items_done_path(@item)
    else
      redirect_to item_path(@item)
    end
  end

  def done
    card = Card.find_by(user_id: current_user.id)
    if card
      Payjp.api_key = ENV["PAYJP_TEST_SECRET"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card = customer.cards.retrieve(card.card_id) 
    end
    @item = Item.find(params[:id])
    render layout: "single"
  end

  def destroy
    if @item.destroy
      redirect_to action: "index"
    else
      flash[:notice] = "削除に失敗しました"
      redirect_to action: "show"
    end
  end

  # 出品ページでカテゴリーのセレクトボックス用。jbuilderとroutes.rbと繋がっています
  def category_children
    @select_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @select_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def search
    @parents = Category.all.order('id ASC').limit(13)
    if params[:q].present?
      params[:q][:name_cont_all] = params[:q][:name_cont_all].split(/[\p{blank}\s]+/)
      params[:q][:category_id_eq_any] = params[:q][:category_id_eq_any].split(/[\p{blank}\s]+/)
      @keyword = Item.ransack(params[:q])
      # @keyword.sorts = 'created_at desc' if @keyword.sorts.empty?
      @items = @keyword.result(distinct: true).includes(:images, :category)
    else
      @items = Item.where("name LIKE(?)", "%#{params[:keyword]}%").includes(:images).order("created_at desc")
      @keyword = Item.ransack()
      params[:q] = { sorts: 'id desc' }
    end    
  end

  private
  def item_params
    params.require(:item).permit(:id, :name, :description, :category_id, :size, :condition, :shipping_fee, :shipping_method, :prefecture, :shipping_date, :price, :status, :seller_id, :buyer_id, :image_validation, {image_files: []}, {delete_image_files: []}).merge(seller_id: current_user.id)
  end

  def pay_params
    params.require(:item).permit(:buyer_id, :status)
  end
  
  def set_item
    @item = Item.find(params[:id])
    @grandchild = Category.find(@item.category_id)
  end

  def authenticate  
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def ramdom_item
    ramdom_item = Item.all.sample
  end

end

app/views/items/_comment.html.haml
.message-content
  .message-form
    = form_for @comment, url: item_comments_path(@item, @comment), class: "message-form" do |f|
      %p
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .message-form__textarea
        = f.text_area :content
      = f.submit "コメントする", class: "single__form__send-btn single__form__send-btn--gray"

app/views/items/_comment_list.html.haml
.modal__window{id: comment.id}
  .modal
    .modal__top
      .modal__top__title
        確認
      .modal__top__comment
        = comment.content
      .modal__top__text
        本当にこのコメントを削除してよろしいですか？
    .modal__form
      .modal__form__btn
        = link_to "キャンセル"
      .modal__form__btn
        = link_to "削除する", item_comment_path(@item,comment), method: :delete


- if comment.user_id == @item.seller_id
  .item__comment
    .item__comment__content
      .item__comment__content-name
        .item__comment__content-name__seller
          = link_to @item.seller.nickname, show_user_plofile_path(@item.seller), method: :get
      .item__comment__content-comment
        .item__comment__content-comment__seller
          %p
            = comment.content
          %span.comment-clock
            = time_format(comment.created_at)
          -if @item.seller_id == current_user&.id
            = link_to "/" do
              = fa_icon "trash-o", class: "delete-icon", "data-id": "#{comment.id}"
        .item__comment__content-balloon__seller
    .item__comment__user
      .item__comment__user-icon
        = image_tag @item.seller.image.url, size: "40x40"
        .item__comment__user-seller
          %p 出品者

- else
  .item__comment
    .item__comment__user
      .item__comment__user-icon
        = image_tag comment.user.image.url, size: "40x40"
    .item__comment__content
      .item__comment__content-name
        .item__comment__content-name__user
          = link_to comment.user.nickname, show_user_plofile_path(comment.user), method: :get
      .item__comment__content-comment
        .item__comment__content-comment__user
          %p
            = comment.content
          %span.comment-clock
            = time_format(comment.created_at)
          -if comment.user_id == current_user&.id
            = link_to do
              = fa_icon "trash-o", class: "delete-icon", "data-id": "#{comment.id}"
        .item__comment__content-balloon

app/views/items/_item-s.html.haml
%section{class: "items-box--s"}
  = link_to item_path(item.id) do
    .items-box--s__photo      
      -image = item.images.first
      -if image
        =image_tag "#{image.image}"
      -if item.status >= 1
        .items-box--s__photo__soldout
          %h2 SOLD
    .items-box--s__body
      %h3{class: "items-box--s__body__name font-2"}
        =item.name
      .items-box--s__body__num
        .items-box--s__body__num__price.font-5
          ="¥ #{item.price.to_s(:delimited)}"

        -if item.favorites.present?
          .items-box__body__num__like.font-2
            =fa_icon "heart-o"
            = item.favorites.count

app/views/items/_item.html.haml
%section{class: "items-box"}
  = link_to item_path(item.id) do
    .items-box__photo      
      - image = item.images.first
      - if image
        = image_tag "#{image.image}"
      - if item.status >= 1
        .items-box__photo__soldout
          %h2 SOLD
    .items-box__body
      %h3{class: "items-box__body__name font-2"}
        = item.name
      .items-box__body__num
        .items-box__body__num__price.font-5
          ="¥ #{item.price.to_s(:delimited)}"
        -if item.favorites.present?
          .items-box__body__num__like.font-2
            =fa_icon "heart-o"
            = item.favorites.count

app/views/items/buy.html.haml
%main.single__page__main
  .single__page__main__container
    .purchase-confirmations
      %h2.purchase-confirmations__head
        購入内容の確認
      .purchase-confirmations__container
        .purchase-confirmations__item
          .purchase-confirmations__item__detail
            -image = @item.images.first
            -if image
              =image_tag "#{image.image}", class: "purchase-confirmations__item__detail__img"
            %p.purchase-confirmations__item__detail__name
              =@item.name
          %p.purchase-confirmations__item__price
            ="¥ #{@item.price}"
            %span 
              =@item.shipping_fee
          %p.purchase-confirmations__item__point
            ポイントはありません
          %p.purchase-confirmations__item__pey-price
            支払い金額
            %span 
              ="¥ #{@item.price}"
          -unless @item.seller_id == current_user&.id
            -if @card && current_user.address
              -if @item.status == 0
                =form_for @item, url: {controller: "items", action: "pay"} do |f|
                  = f.text_field :status, value: 1, class: "purchase-form-hidden"
                  = f.text_field :buyer_id, value: current_user.id, class: "purchase-form-hidden"
                  %button.purchase-button{type: "submit"}
                    購入する
              -else
                %button.purchase-button--sold
                  売り切れです
            -else
              %p.purchase-button__notice
                支払い方法と配送先を登録してください
              %button.purchase-button--sold
                購入する

  
      -# ユーザーのデータベースができてから表示
      .purchase-confirmations__container
        %section.buy-user-info
          .buy-user-info__address
            %h3 配送先
            -if current_user.address
              %address
                = "〒#{current_user.address.postal_code}"
                %br 
                = current_user.address.prefecture + current_user.address.municipalities + current_user.address.address
                -if current_user.address.building
                  = current_user.address.building
                %br
                = "#{current_user.address.first_name + current_user.address.last_name}"

            =link_to edit_address_path, class: "buy-user-info__fix" do 
              %span
                変更する
                =fa_icon "angle-right"
      .purchase-confirmations__container
        -if @card
          %section.buy-user-info
            .buy-user-info__credit
              %h3 支払い方法
              %p.buy-user-info__credit__number
                = "********" + @card.last4
                %br
                = @card.exp_month.to_s + " / " + @card.exp_year.to_s.slice(2,3)
              = fa_icon "cc-#{@card.brand.downcase}", class: "single__icon single__icon--mail"
              =link_to mypage_card_path, class: "buy-user-info__fix" do 
                %span
                  変更する
                  =fa_icon "angle-right"
        -else
          %section.buy-user-info
            .buy-user-info__credit
              %h3 支払い方法
              %p.buy-user-info__credit__number
                = ""
                %br
                = " / " 
              =link_to mypage_card_path, class: "buy-user-info__fix" do 
                %span
                  変更する
                  =fa_icon "angle-right"

 

app/views/items/done.html.haml
%main.single__page__main
  .single__page__main__container
    .purchase-confirmations
      .purchase-confirmations__container
        .purchase-confirmations__notice

          %h3.purchase-confirmations__notice__wait
            %span
              =fa_icon "clock-o"
            発送をお待ちください
          %p.purchase-confirmations__notice__message
            出品者からの発送通知をお待ちください
      %h2.purchase-confirmations__head
        購入が完了しました
      .purchase-confirmations__container
        .purchase-confirmations__item

          -image = @item.images.first
          -if image
            =image_tag "#{image.image}", class: "purchase-confirmations__item__detail__img--done"
          %p.purchase-confirmations__item__detail__name
            =@item.name

      .purchase-confirmations__container
        %p.purchase-confirmations__item__price
          ="¥ #{@item.price}"
          %span 
            =@item.shipping_fee


  
      -# ユーザーのデータベースができてから表示
      .purchase-confirmations__container
        %section.buy-user-info
          .buy-user-info__address
            %h3 配送先
            -if current_user.address
              %address
                = "〒#{current_user.address.postal_code}"
                %br 
                = current_user.address.prefecture + current_user.address.municipalities + current_user.address.address
                -if current_user.address.building
                  = current_user.address.building
                %br
                = "#{current_user.address.first_name + current_user.address.last_name}"

      .purchase-confirmations__container
        -if @card
          %section.buy-user-info
            .buy-user-info__credit
              %h3 支払い方法
              %p.buy-user-info__credit__number
                = "********" + @card.last4
                %br
                = @card.exp_month.to_s + " / " + @card.exp_year.to_s.slice(2,3)
              = fa_icon "cc-#{@card.brand.downcase}", class: "single__icon single__icon--mail"

        -else
          %section.buy-user-info
            .buy-user-info__credit
              %h3 支払い方法
              %p.buy-user-info__credit__number
                = ""
                %br
                = " / " 

      .purchase-confirmations__container
        .purchase-confirmations__done
          %h3 発送通知後の流れ
          .purchase-confirmations__done__face
            .item-content__detail-table__face--good
              = fa_icon "smile-o", class: "good-icon"
              %span.item-content__detail-table__face__name
                
            .item-content__detail-table__face--normal
              = fa_icon "meh-o", class: "normal-icon"
              %span.item-content__detail-table__face__name
                
            .item-content__detail-table__face--bad
              = fa_icon "frown-o", class: "bad-icon"
              %span.item-content__detail-table__face__name
                
          %p
            商品を受け取ったら
            %br
            出品者の評価をしましょう。
            %br
            購入代金が出品者に振り込まれます。
            %br
            評価後に取引は完了です。
          
          = link_to "マイページへもどる", mypage_index_path, class: "purchase-confirmations__done__link"

app/views/items/index.html.haml
%main{class: 'white'}
  .slideshow
    .slideshow__banner
      .top-main-visual
        .top-main-visual__wrapper
          .top-main-visual__wrapper__content
            %h2.top-main-visual__wrapper__content__title
              スマホでかんたん
              %br フリマアプリ
            %h2.sp-top-main-visual__title
              スマホで
              %br かんたん
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐ出品できる
              %br 購入時も安心な独自システムのアプリです
            .top-main-visual__wrapper__content__store
              =link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", class: "pull-left", target: "_blank" do
                = image_tag 'app-store.svg'
              =link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", class:"pull-left", target: "_blank" do
                = image_tag 'google-play.svg'
          = image_tag 'main_content_pc.png', alt: "main-content", class: "phone-img"
    .slideshow__banner
      .top-main-visual--camp
        =image_tag "camp.png", class: "top-main-visual--camp__img"
    

  -# カテゴリ
  %section.pickup
    %h2{class: "pickup__head"}
      ピックアップカテゴリー
    %section{class: "items-box__container"}
      %h3{class: "text-center"} 
        = link_to "レディース新着アイテム", category_path(1)
      .items-box__content
        -@ladies_items.each do |item|
          = render partial: "item", locals: {item: item}
      .view-all
        = link_to "すべての商品を見る", category_path(1)

    %section{class: "items-box__container"}
      %h3{class: "text-center"} 
        = link_to "メンズ新着アイテム", category_path(2)
      .items-box__content
        -@mens_items.each do |item|
          = render partial: "item", locals: {item: item}
      .view-all
        = link_to "すべての商品を見る", category_path(2)

    %section{class: "items-box__container"}
      %h3{class: "text-center"} 
        = link_to "ベビー・キッズ新着アイテム", category_path(3)
      .items-box__content
        -@babys_items.each do |item|
          = render partial: "item", locals: {item: item}
      .view-all
        = link_to "すべての商品を見る", category_path(3)

    %section{class: "items-box__container"}
      %h3{class: "text-center"} 
        = link_to "コスメ・香水・美容新着アイテム", category_path(7)
      .items-box__content
        -@cosmetics_items.each do |item|
          = render partial: "item", locals: {item: item}
      .view-all
        = link_to "すべての商品を見る", category_path(7)


  -# 商品一覧
  %section.pickup
    %h2{class: "pickup__head"}
      商品一覧
    %section{class: "items-box__container"}
      .items-box__content
        = render @items

app/views/items/new.html.haml
%main.single__page__main
  .single__page__main__container
    %h2.single__page__main__head
      商品の情報を入力
    = form_for @item, url: items_path, html: {class: "single__form single__form--sell", id: "single__form--sell" } do |f|
      = render partial: 'item-form', locals: { f: f }
      .sell-content
        %div
          %p.single__field__text
            = link_to "禁止されている出品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/" , class:"sell-notice"
            、
            = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/", class:"sell-notice"
            を必ずご確認ください。
        
            %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/", class:"sell-notice"
            は犯罪であり処罰される可能性があります。
          
            %br
            また、出品をもちまして
            = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/", class:"sell-notice"
            に同意したことになります。

        = f.submit "出品する", class: "single__form__send-btn", id: "sell-submit"
        = link_to root_path do
          = f.submit "もどる", class: "single__form__send-btn single__form__send-btn--gray single__form__send-btn--small" 

.modal__window
  .modal
    .modal__header
      出品が完了しました
    .modal__body
      .modal__body__text
        あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。
      .modal__body__btn
        = link_to "続けて出品する", items_sell_path, class: "modal__body__btn__link"
      = link_to "商品ページへ行ってシェアする", "/", class: "modal__body__link"
    

app/views/items/show.html.haml
-breadcrumb :item_name
.show-container
  .item__box-container
    %h1.item__name
      = @item.name
    .item__main-content
      .item__photo
        - if @item.status >= 1
          .item__photo__soldout
            %h2 SOLD
        .item__photo__slide
          -@item.images.each do |image|
            =image_tag "#{image.image}", class: "item__photo__slide__img"
        .item__photo__container
          -@item.images.each_with_index do |image,i|
            =image_tag "#{image.image}", class: "item__photo__container__img","data-id": "#{i}"

      %table.item__detail-table
        %tboby
          %tr
            %th 出品者
            %td
              = link_to @item.seller.nickname, show_user_plofile_path(@item.seller), method: :get, class: "user-name-link"
              .item-content__detail-table__face
                .item-content__detail-table__face--good
                  = fa_icon "smile-o", class: "good-icon"
                  %span.item-content__detail-table__face__name
                    10
                .item-content__detail-table__face--normal
                  = fa_icon "meh-o", class: "normal-icon"
                  %span.item-content__detail-table__face__name
                    10
                .item-content__detail-table__face--bad
                  = fa_icon "frown-o", class: "bad-icon"
                  %span.item-content__detail-table__face__name
                    10

          %tr
            %th カテゴリー
            %td
              =link_to category_path(@grandchild.root.id),class:'aBlue' do
                = @grandchild.root.name
              =link_to category_path(@grandchild.parent.id),class:'aBlue' do
                .item-category-sub
                  = fa_icon 'chevron-right',class:'item-category__icon'
                  = @grandchild.parent.name
              =link_to category_path(@grandchild.id),class:'aBlue' do
                .item-category-sub-sub
                  = fa_icon 'chevron-right',class:'item-category__icon'
                  = @grandchild.name
          %tr
            %th 商品のサイズ
            %td 
              = @item.size
          %tr
            %th 商品の状態
            %td 
              = @item.condition
          %tr
            %th 配送料の負担
            %td 
              = @item.shipping_fee
          %tr
            %th 配送の方法
            %td
              = @item.shipping_method
          %tr
            %th 配送元地域
            %td
              = @item.prefecture
          %tr
            %th 配達日の目安
            %td
              = @item.shipping_date

    .item__price-box
      %span.item__price-box__price
        = "¥ #{@item.price.to_s(:delimited)}"
      %span.item__price-box__tax
        (税込)
      %span.item__price-box__shipping-fee
        = @item.shipping_fee
    -unless @item.seller_id == current_user&.id
      -if @item.status == 0
        =link_to items_buy_path, class: "item__buy-btn" do
          購入画面に進む
      - else
        %button.item__buy-btn--sold
          売り切れです

    %section.item__description
      %p.item__description__innner
        = @item.description

    .item__button-container
      .item__button__left
        = render "favorites/favorite" #いいね! 部分テンプレート
    
        %button.item__button.item__button__report
          =fa_icon "flag-o"
          %span 不適切な商品の報告
      .item__button__right
        =link_to "https://www.mercari.com/jp/safe/description/" do
          =fa_icon "lock"
          %span.aBlue あんしん・あんぜんへの取り組み

  -if @item.seller_id == current_user&.id
    .item__detail-message
      .message-container
        .message-content
          .mypage__content__tab-content__item-list__btn
            .mypage__content__tab-content__item-list__btn--edit
              = link_to "商品の編集", edit_item_path(@item), method: :get, class: "item-edit"
          .mypage-content--choose
            or
          .mypage__content__tab-content__item-list__btn
            .mypage__content__tab-content__item-list__btn--gray
              = link_to "この商品を削除する", item_path(@item), method: :delete, class: "item-delete", data: { confirm: '削除しますか？' }


  .item__detail-message
    .message-container
      .item__comments
        = render partial: "comment_list", collection: @comments, as: :comment

      - if user_signed_in?
        = render "comment"

  %ul.nav-item__link-prev-next
    %li.nav-item__link-prev
      -pre_item = ramdom_item
      =link_to item_path(pre_item),class:'aBlue' do
        =fa_icon "angle-left"
        = pre_item.name
    %li.nav-item__link-next
      -next_item = ramdom_item
      =link_to item_path(next_item),class:'aBlue' do
        = next_item.name
        =fa_icon "angle-right"
        
  .item__social-media-box
    %ul.item__social-media-box__links
      %li
        =link_to "http://www.facebook.com" do
          =fa_icon "facebook-square", class:"icon-facebook"
      %li
        =link_to "http://www.twitter.com" do
          =fa_icon "twitter-square", class:"icon-twitter"
      %li
        =link_to "http://www.pinterest.com" do
          =fa_icon "pinterest-square", class:"icon-pinterest"

  .item-other
    %section.item-other__user-items
      %h2.item-other__user-items__head
        = link_to show_user_plofile_path(@item.seller.id), method: :get, class: "link item-link" do
          ="#{@item.seller.nickname}さんのその他の出品"
      .item-other__user-items__contents
        %section{class: "items-box__container"}
          .items-box__content
            = render @user_items