config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    # passwords: 'users/passwords'
    # ToDo: facebook認証に応じて追加
    # omniauth_callbacks: "users/omniauth_callbacks"
  }
  as :user do
    get 'users/sign_up/registration', to: 'users/registrations#new', as: :user_registration
    get 'users/sign_up', to: 'users/registrations#register', as: :register_user_registration
    post 'users/sign_up/sms_confirmation', to: 'users/registrations#validation', as: :user_validation
    get 'users/sign_up/sms_confirmation', to: 'users/registrations#sms_confirmation', as: :sms_confirmation_user_registration
    post 'users/sign_up/add_phone_number', to: 'users/registrations#add_phone_number', as: :add_phone_number
    get 'users/sign_up/sms_confirmation/sms', to: 'users/registrations#verification_code_input', as: :verification_code_input
    post 'users/sign_up/verification', to: 'users/registrations#verification', as: :verification
    get 'users/sign_up/address', to: 'users/registrations#address', as: :address_user_registration
    get 'users/sign_up/credit_card', to: 'users/registrations#credit_card', as: :credit_card_user_registration
    get 'users/sign_up/finish', to: 'users/registrations#finish', as: :finish_user_registration
    post 'users', to: 'users/registrations#create', as: :create_user_registration
    get 'users/:id', to: 'users#show', as: :show_user_plofile
    # get 'mypage/email_password', to: 'users/registrations#edit', as: :email_password_mypage_index
    # get 'mypage/email_password/confirmation', to: 'users/registrations#update_confirmation', as: :email_password_confirmation_mypage_index
    put 'mypage/email_password', to: 'users/registrations#update', as: :update_user_registration
  end

  root to: "items#index"
  resources :mypage, only: [:index] do
    collection do
      get "notification", "todo", "purchase", "purchased", "news", "support", "sales", "point", "profile", "email_password", "confirmation", "identification", "sms_confirmation", "help_center"
    end
  end

  as :mypage do
    post "identification", to: "mypage#create_identification"
    patch "identification", to: "mypage#create_identification"
    get "mypage/like/history", to: "mypage#like"
    get "mypage/listings/listing", to: "mypage#listing"
    get "mypage/listings/in_progress", to: "mypage#in_progress"
    get "mypage/listings/completed", to: "mypage#completed"
    get "mypage/review/history", to: "mypage#review"
    get "logout", to: "mypage#logout"
    patch "mypage/profile", to: "mypage#update_profile"
  end

  as :address do 
    get 'mypage/deliver_address', to: 'addresses#edit', as: :edit_address  
    post 'address', to: 'addresses#create', as: :create_address
    patch 'address', to: 'addresses#update', as: :update_address
  end
  
  as :items do
    get "transaction/done/:id", to: "items#done", as: :items_done
    get "transaction/buy/:id", to: "items#buy", as: :items_buy
    patch "transaction/pay/:id", to: "items#pay", as: :items_pay
    get "items/sell", to: "items#new", as: :items_sell
    get "items/search", to: "items#search"
  end
  
  resources :items, except: :new do
    collection do
      get "category_parent", defaults: {format:'json'} 
      get 'category_children', defaults: {format:'json'}
      get 'category_grandchildren', defaults: {format:'json'}
    end
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories,  only: [:index, :show] 
  resources :brands,  only: [:index, :show]
  resources :cards, only: [:new, :create, :destroy,]
  as :cards do
    get "mypage/card", to: "cards#card"
  end

  # 一番下に置いてください↓
  get '*path', controller: 'application', action: 'render_404'

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def new
    @card = Card.new
  end

  def card
    card = Card.find_by(user_id: current_user.id)
    if card
      Payjp.api_key = ENV["PAYJP_TEST_SECRET"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card = customer.cards.retrieve(card.card_id) 
    end
  end

  def create
    Payjp.api_key = ENV["PAYJP_TEST_SECRET"]
    customer = Payjp::Customer.create
    card = customer.cards.create(card: params[:payjp_token])
    @card = Card.create(user_id: current_user.id, customer_id: customer.id, card_id: card.id)
    
    # credit_cardの登録はsign_upのcredit_cardとmypageのnewの両方のアクションから呼ばれるため、条件分岐で行き先を指定
    path = Rails.application.routes.recognize_path(request.referer)
    if path[:action] == "credit_card"
      redirect_to :finish_user_registration
    else
      redirect_to :mypage_card
    end
  end

  def destroy
    @card = Card.find_by(user_id: current_user.id)   
    Payjp.api_key = ENV["PAYJP_TEST_SECRET"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    @card.destroy
    redirect_to :mypage_card
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/card.html.haml
-breadcrumb :card
%main.mypage
  .mypage__container
    .mypage__contents
      .single__page__main
        .single__page__main__container
          %h2.single__page__main__head
            支払い方法
          .single__form
            .single__field.single__field--large
              %h3.single__field__text
                クレジットカード一覧
            - if current_user.card
              .single__field.single__field--flex
                .single__field__left
                  .single__field__text
                    = fa_icon "cc-#{@card.brand.downcase}", class: "single__icon single__icon--mail"
                  .single__field__text
                    ="********" + @card.last4
                  .single__field__text
                    = @card.exp_month.to_s + " / " + @card.exp_year.to_s.slice(2,3)
                .single__field__right
                  =link_to card_path(@card), method: :delete do
                    %button.single__mini-btn
                      削除する

            - else
              .single__field
                = link_to new_card_path, class: "single__btn single__btn--red", id: "mail-btn" do
                  = fa_icon "credit-card lg", class: "single__icon single__icon--mail"
                  クレジットカードを追加する
          .single__form--box
            .single__field
              = link_to "支払い方法について>", "/", class: "single__field__text single__field__text__link single__field__text--right"
    .mypage__side 
      =render "shared/sidebar"

app/views/cards/new.html.haml
:ruby
  cardlists = ["visa-card.svg", "mastercard.svg", "saison-card.svg" ,"jcb-card.svg", "american-express-card.svg", "diners-club-International.svg", "discover-card.svg"]

%main.mypage
  .mypage__container
    .mypage__contents
      .single__page__main
        .single__page__main__container
          %h2.single__page__main__head
            支払い方法
          = form_with(url: cards_path, html: {method: :post, class: "single__form", id: "charge-form"}) do |f|
            .single__field
              .single__field__label
                = f.label :number, "カード番号"
                %span.single__field__require 必須
              .single__field__input
                = f.text_field :number, placeholder: "半角数字のみ", maxlength: "16", name: "number", type: "text", id: "payment_card_no", class: "number input-default"
              - cardlists.each do |card|
                = image_tag "#{card}", class: "single__icon--card"
            .single__field
              .single__field__label
                = f.label :valid, "有効期限"
                %span.single__field__require 必須
              .single__field--flex
                .single__field__select.single__field__select--small
                  %select.exp_month#card_expire_mm{maxlength: "2", name: "exp_month", type: "text"}
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                %span 月
                .single__field__select.single__field__select--small
                  %select.exp_year#card_expire_yy{maxlength: "4", name: "exp_year", type: "text"}
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                    %option{value: "2030"}30
                %span 年
            .single__field
              .single__field__label
                = f.label :number, "セキュリティコード"
                %span.single__field__require 必須
              .single__field__input
                = f.text_field :number, placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "3", name: "cvc", type: "text", id: "cvc_code", class: "cvc input-default"
              = link_to "カード裏面の番号とは？", "/", class: "single__field__text single__field__text__link single__field__text--right"
            = f.submit "登録完了", class: "single__form__send-btn", id: "submit-charge"
    .mypage__side 
      =render "shared/sidebar"