config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions',
    # passwords: 'users/passwords'
    # ToDo: facebook認証に応じて追加
    # omniauth_callbacks: "users/omniauth_callbacks"
  }
  as :user do
    get 'users/sign_up/registration', to: 'users/registrations#new', as: :user_registration
    get 'users/sign_up', to: 'users/registrations#register', as: :register_user_registration
    post 'users/sign_up/sms_confirmation', to: 'users/registrations#validation', as: :user_validation
    get 'users/sign_up/sms_confirmation', to: 'users/registrations#sms_confirmation', as: :sms_confirmation_user_registration
    post 'users/sign_up/add_phone_number', to: 'users/registrations#add_phone_number', as: :add_phone_number
    get 'users/sign_up/sms_confirmation/sms', to: 'users/registrations#verification_code_input', as: :verification_code_input
    post 'users/sign_up/verification', to: 'users/registrations#verification', as: :verification
    get 'users/sign_up/address', to: 'users/registrations#address', as: :address_user_registration
    get 'users/sign_up/credit_card', to: 'users/registrations#credit_card', as: :credit_card_user_registration
    get 'users/sign_up/finish', to: 'users/registrations#finish', as: :finish_user_registration
    post 'users', to: 'users/registrations#create', as: :create_user_registration
    get 'users/:id', to: 'users#show', as: :show_user_plofile
    # get 'mypage/email_password', to: 'users/registrations#edit', as: :email_password_mypage_index
    # get 'mypage/email_password/confirmation', to: 'users/registrations#update_confirmation', as: :email_password_confirmation_mypage_index
    put 'mypage/email_password', to: 'users/registrations#update', as: :update_user_registration
  end

  root to: "items#index"
  resources :mypage, only: [:index] do
    collection do
      get "notification", "todo", "purchase", "purchased", "news", "support", "sales", "point", "profile", "email_password", "confirmation", "identification", "sms_confirmation", "help_center"
    end
  end

  as :mypage do
    post "identification", to: "mypage#create_identification"
    patch "identification", to: "mypage#create_identification"
    get "mypage/like/history", to: "mypage#like"
    get "mypage/listings/listing", to: "mypage#listing"
    get "mypage/listings/in_progress", to: "mypage#in_progress"
    get "mypage/listings/completed", to: "mypage#completed"
    get "mypage/review/history", to: "mypage#review"
    get "logout", to: "mypage#logout"
    patch "mypage/profile", to: "mypage#update_profile"
  end

  as :address do 
    get 'mypage/deliver_address', to: 'addresses#edit', as: :edit_address  
    post 'address', to: 'addresses#create', as: :create_address
    patch 'address', to: 'addresses#update', as: :update_address
  end
  
  as :items do
    get "transaction/done/:id", to: "items#done", as: :items_done
    get "transaction/buy/:id", to: "items#buy", as: :items_buy
    patch "transaction/pay/:id", to: "items#pay", as: :items_pay
    get "items/sell", to: "items#new", as: :items_sell
    get "items/search", to: "items#search"
  end
  
  resources :items, except: :new do
    collection do
      get "category_parent", defaults: {format:'json'} 
      get 'category_children', defaults: {format:'json'}
      get 'category_grandchildren', defaults: {format:'json'}
    end
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories,  only: [:index, :show] 
  resources :brands,  only: [:index, :show]
  resources :cards, only: [:new, :create, :destroy,]
  as :cards do
    get "mypage/card", to: "cards#card"
  end

  # 一番下に置いてください↓
  get '*path', controller: 'application', action: 'render_404'

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  def index
    @purchase_items = Item.where(buyer_id: current_user, status: 1)
    @purchased_items = Item.where(buyer_id: current_user, status: 2)
    @items = Item.where(seller_id: current_user)
  end

  def listing
    @items = Item.where(seller_id: current_user, status: 0)
  end

  def in_progress
    @items = Item.where(seller_id: current_user, status: 1)
  end

  def completed
    @items = Item.where(seller_id: current_user, status: 2)
  end

  def purchase
    @items = Item.where(buyer_id: current_user, status: 1)
  end

  def purchased
    @items = Item.where(buyer_id: current_user, status: 2)
  end

  def profile
  end
  
  def like
    @items = current_user.favorite_items
  end

  def update_profile
    if current_user.update(user_profile_params)
      redirect_to  profile_mypage_index_path, notice: "変更しました"
    else
      render :index
    end
  end

  def logout  
  end

  def identification
    @identification = Identification.find_or_initialize_by(user_id: current_user.id)
  end

  def create_identification
    @identification = Identification.find_or_initialize_by(user_id: current_user.id)
    if @identification.update(identification_params)
      redirect_to identification_mypage_index_path, notice: "変更しました"
    else
      render "mypage/identification"
    end
  end

  private
  def identification_params
    params.require(:identification).permit(:postal_code, :prefecture, :municipalities, :address, :building).merge(user_id: current_user.id)
  end

  def user_profile_params
    params.require(:user).permit(:nickname, :introduce, :image)
  end
end

app/helpers/mypage_helper.rb
module MypageHelper

  def set_item_status(status)
    if status == 0
      tag.div "出品中", class: "mypage__content__tab-content__item-list__body__detail__status"
    elsif status == 1
      tag.div "取引中", class: "mypage__content__tab-content__item-list__body__detail__status mypage__content__tab-content__item-list__body__detail__status--red"
    elsif status == 2
      tag.div "取引完了", class: "mypage__content__tab-content__item-list__body__detail__status mypage__content__tab-content__item-list__body__detail__status--gray"
    end
  end

end

app/views/mypage/_mypage-tab-lists.html.haml
- if announces.length == 0
  %li.mypage__content__tab-content__item-list--none
    情報はありません
- else 
  - announces.each do |announce|
    %li
      = link_to mypage_index_path, class: "mypage__content__tab-content__item-list__link" do
        .mypage__content__tab-content__item-list__icon
          = image_tag "mercari_icon.png", size: "48x48"
        .mypage__content__tab-content__item-list__body
          .mypage__content__tab-content__item-list__body--text #{announce[:Name]}
          .mypage__content__tab-content__item-list__body--icon-time
            = fa_icon 'clock-o', class: 'icon'
          %span 1分前
        .mypage__content__tab-content__item-list__right-icon
          =fa_icon "angle-right", class: 'icon-chek'
  %li.mypage__content__tab-content__item-list__btn
    .mypage__content__tab-content__item-list__btn--gray
      = link_to user_path(current_user) do
        一覧を見る

app/views/mypage/_mypage-tabs.html.haml
- if active
  %li.mypage__content__tab.active-mypage-tab
    %h3.mypage__content__tabs__head
      = link_to path do
        = title
- else
  %li.mypage__content__tab
    %h3.mypage__content__tabs__head
      = link_to path do
        = title

app/views/mypage/_mypage_tab_item.html.haml
%li
  = link_to item_path(item), class: "mypage__content__tab-content__item-list__link" do
    .mypage__content__tab-content__item-list__icon
      = image_tag "#{item.images[0].image}", size: "48x48"
    .mypage__content__tab-content__item-list__body
      .mypage__content__tab-content__item-list__body--text
        = item.name
      .mypage__content__tab-content__item-list__body__detail
        - if item.status == 0
          .mypage__content__tab-content__item-list__body__detail__favorites
            = fa_icon "heart-o"
            = item.favorites.count
          .mypage__content__tab-content__item-list__body__detail__comments
            = fa_icon 'comments'
            = item.comments.count
        = set_item_status(item.status)
        
    .mypage__content__tab-content__item-list__right-icon
      = fa_icon "angle-right", class: 'icon-chek'

app/views/mypage/confirmation.html.haml
-breadcrumb :email_password
%main.mypage
  .mypage__container
    .mypage__content
      .single__page__main
        .single__page__main__container
          %h2.single__page__main__head
            メールアドレス/パスワードの変更
      .single__page__main
        .single__page__main__container
          .single__form.single__form--big
            %p.single__field__text  
              メールアドレス/パスワードを変更しました。
    .mypage__side
      =render "shared/sidebar"

app/views/mypage/email_password.html.haml
-breadcrumb :email_password
%main.mypage
  .mypage__container
    .mypage__contents
      .single__page__main
        .single__page__main__container
          %h2.single__page__main__head
            メール/パスワード
          = form_for current_user, url: update_user_registration_path, html: { method: :put, class: "single__form" } do |f|
            -# = devise_error_messages!
            .single__field
              .single__field__label
                = f.label :email, "メールアドレス"
                %span.single__field__require 必須
              .single__field__input
                = f.email_field :email, placeholder: "PC・携帯どちらでも可"

            .single__field
              .single__field__label
                = f.label :current_password, "現在のパスワード"
                %span.single__field__require 必須
              .single__field__input
                = f.password_field :current_password, placeholder: "6文字以上"

            .single__field
              .single__field__label
                = f.label :password, "新しいパスワード(確認)"
                %span.single__field__require 必須
              .single__field__input
                = f.password_field :password, placeholder: "6文字以上"
              
            .single__field
              .single__field__label
                = f.label :password_confirmation, "新しいパスワード(確認)"
                %span.single__field__require 必須
              .single__field__input
                = f.password_field :password_confirmation, placeholder: "6文字以上"
            .single__field
              %p.single__field__text
                パスワードを設定したい場合は上記をすべて入力してください。（設定しない場合は空欄）
            .single__field
              = f.submit "変更する", class: "single__form__send-btn"
    .mypage__side
      =render "shared/sidebar"

app/views/mypage/in_progress.html.haml
:ruby
  titles = ["出品中", "取引中", "売却済み"]
  path = [mypage_listings_listing_path, mypage_listings_in_progress_path, mypage_listings_completed_path]

  announces = [{
    Name:"aさんの商品を購入！", url:"#"
  },{
    Name:"bさんの商品を購入！", url:"#"
  },{
    Name:"cさんの商品を購入！", url:"#"
  }]


-breadcrumb :in_progress
%main.mypage
  .mypage__container
    .mypage__content
      .mypage__content__head.mypage__content__head--text
        出品した商品
      %section.mypage__content__tab-container
        %ul.mypage__content__tabs
          = render partial: "mypage-tabs", locals: { active: false, title: titles[0], path: path[0] }
          = render partial: "mypage-tabs", locals: { active: true, title: titles[1], path: path[1] }
          = render partial: "mypage-tabs", locals: { active: false, title: titles[2], path: path[2] }
        .mypage__content__tab-content
          %ul.mypage__content__tab-content__item-list.show-mypage-tab
            - if @items.exists?
              - @items&.each do |item|
                = render partial: "mypage_tab_item", locals: {item: item}
            - else 
              %li.mypage__content__tab-content__item-list--none
                取引中の商品はありません

    .mypage__side
      =render "shared/sidebar"

app/views/mypage/index.html.haml
:ruby
  first_titles = ["お知らせ", "やることリスト"]
  first_path = [notification_mypage_index_path, todo_mypage_index_path]
  second_titles = ["取引中", "過去の取引"]
  second_path = [purchase_mypage_index_path, purchased_mypage_index_path]

-breadcrumb :mypages
%main.mypage
  .mypage__container
    .mypage__contents
      .mypage__content
        .mypage__content__head.mypage__content__head--image
          %section.mypage__content__head__user-icon
            = link_to show_user_plofile_path(current_user) do
              %figure
                = image_tag current_user.image.url, size: "60x60"
              %h2.mypage__content__head__user-icon__name.bold
                = current_user.nickname
              .mypage__content__head__user-icon__number
                .mypage__content__head__user-icon__number--rate
                  評価
                  %span.bold
                    0
                .mypage__content__head__user-icon__number--display
                  出品数
                  %span.bold
                    = current_user.selling_items.count + current_user.sold_items.count


        %section.mypage__content__tab-container
          %ul.mypage__content__tabs
            = render partial: "mypage-tabs", locals: { active: true, title: first_titles[0], path: first_path[0] } 
            = render partial: "mypage-tabs", locals: { active: false, title: first_titles[1], path: first_path[1] } 
          .mypage__content__tab-content
            %ul.mypage__content__tab-content__item-list.show-mypage-tab
              = render partial: "mypage-tab-lists", locals: { announces: [] }
            %ul.mypage__content__tab-content__item-list
              = render partial: "mypage-tab-lists", locals: { announces: [] }
          

      .mypage__content
        .mypage__content__head.mypage__content__head--text
          購入した商品
        %section.mypage__content__tab-container
          %ul.mypage__content__tabs
            = render partial: "mypage-tabs", locals: { active: true, title: second_titles[0], path: second_path[0] }
            = render partial: "mypage-tabs", locals: { active: false, title: second_titles[1], path: second_path[1] }
          .mypage__content__tab-content
            %ul.mypage__content__tab-content__item-list.show-mypage-tab
              - if @purchase_items.exists?
                - @purchase_items&.each do |item|
                  = render partial: "mypage_tab_item", locals: {item: item}
              - else
                %li.mypage__content__tab-content__item-list--none
                  取引中の商品はありません
            %ul.mypage__content__tab-content__item-list
              - if @purchased_items.exists?
                - @purchased_items&.each do |item|
                  = render partial: "mypage_tab_item", locals: {item: item}
              - else
                %li.mypage__content__tab-content__item-list--none
                  売却済みの商品はありません
              

    .mypage__side
      =render "shared/sidebar"

app/views/mypage/like.html.haml
%main.mypage
  %main.mypage__container
    .mypage__contents
      .mypage__content
        %section.mypage__content__setting-profile
          %h2.mypage__content__setting-profile__title いいね！一覧
          %section.mypage__content__tab-container
            .mypage__content__tab-content
              - if @items.length == 0
                .mypage__content__tab-content__item-list--none
                  いいね！がありません
              - else 
                - @items.each do |item|
                  = link_to item_path(item),class: "mypage__content__tab-content__item-list__link" do
                    .mypage__content__tab-content__item-list__icon 
                      - image = item.images.first
                      - if image
                        =image_tag "#{image.image}",size: "48x48"
                    .mypage__content__tab-content__item-list__body
                      .mypage__content__tab-content__item-list__body--text
                        =item.name
                      .mypage__content__tab-content__item-list__body--text
                        ="¥ #{item.price.to_s(:delimited)}"
                    .mypage__content__tab-content__item-list__right-icon
                      =fa_icon "angle-right", class: 'icon-chek'

    .mypage__side
      =render "shared/sidebar"

app/views/mypage/listing.html.haml
:ruby
  titles = ["出品中", "取引中", "売却済み"]
  path = [mypage_listings_listing_path, mypage_listings_in_progress_path, mypage_listings_completed_path]


-breadcrumb :listing
%main.mypage
  .mypage__container
    .mypage__content
      .mypage__content__head.mypage__content__head--text
        出品した商品
      %section.mypage__content__tab-container
        %ul.mypage__content__tabs
          = render partial: "mypage-tabs", locals: { active: true, title: titles[0], path: path[0] }
          = render partial: "mypage-tabs", locals: { active: false, title: titles[1], path: path[1] }
          = render partial: "mypage-tabs", locals: { active: false, title: titles[2], path: path[2] }
        .mypage__content__tab-content
          %ul.mypage__content__tab-content__item-list.show-mypage-tab
            - if @items.exists?
              - @items&.each do |item|
                = render partial: "mypage_tab_item", locals: {item: item}
              -# = render partial: "mypage-tab-item", collection: @items, as: item
            - else 
              %li.mypage__content__tab-content__item-list--none
                出品中の商品はありません
    .mypage__side
      =render "shared/sidebar"

app/views/mypage/notification.html.haml
:ruby
  titles = ["お知らせ", "やることリスト"]
  path = [notification_mypage_index_path, todo_mypage_index_path]


-breadcrumb :notification

%main.mypage
  .mypage__container
    .mypage__content
      %section.mypage__content__tab-container
        %ul.mypage__content__tabs
          = render partial: "mypage-tabs", locals: { active: true, title: titles[0], path: path[0] } 
          = render partial: "mypage-tabs", locals: { active: false, title: titles[1], path: path[1] } 
          -# = render partial: "mypage-tabs", locals: { active: false. title: titles[1], path: path[1] } 
        .mypage__content__tab-content
          %ul.mypage__content__tab-content__item-list.show-mypage-tab
            = render partial: "mypage-tab-lists", locals: { announces: [] }


    .mypage__side
      =render "shared/sidebar"

app/views/mypage/purchase.html.haml
:ruby
  titles = ["取引中", "過去の取引"]
  path = [purchase_mypage_index_path, purchased_mypage_index_path]

  announces = [{
    Name:"aさんの商品を購入！", url:"#"
  },{
    Name:"bさんの商品を購入！", url:"#"
  },{
    Name:"cさんの商品を購入！", url:"#"
  }]


-breadcrumb :purchase
%main.mypage
  .mypage__container
    .mypage__content
      .mypage__content__head.mypage__content__head--text
        購入した商品
      %section.mypage__content__tab-container
        %ul.mypage__content__tabs
          = render partial: "mypage-tabs", locals: { active: true, title: titles[0], path: path[0] }
          = render partial: "mypage-tabs", locals: { active: false, title: titles[1], path: path[1] }
        .mypage__content__tab-content
          %ul.mypage__content__tab-content__item-list.show-mypage-tab
            - if @items.exists?
              - @items&.each do |item|
                = render partial: "mypage_tab_item", locals: {item: item}
            - else
              %li.mypage__content__tab-content__item-list--none
                売却済みの商品はありません

    .mypage__side
      =render "shared/sidebar"

app/views/mypage/purchased.html.haml
:ruby
  titles = ["取引中", "過去の取引"]
  path = [purchase_mypage_index_path, purchased_mypage_index_path]

  announces = [{
    Name:"aさんの商品を購入！", url:"#"
  },{
    Name:"bさんの商品を購入！", url:"#"
  },{
    Name:"cさんの商品を購入！", url:"#"
  }]


-breadcrumb :purchased
%main.mypage
  .mypage__container
    .mypage__content
      .mypage__content__head.mypage__content__head--text
        購入した商品
      %section.mypage__content__tab-container
        %ul.mypage__content__tabs
          = render partial: "mypage-tabs", locals: { active: false, title: titles[0], path: path[0] }
          = render partial: "mypage-tabs", locals: { active: true, title: titles[1], path: path[1] }
        .mypage__content__tab-content
          %ul.mypage__content__tab-content__item-list.show-mypage-tab
            - if @items.exists?
              - @items&.each do |item|
                = render partial: "mypage_tab_item", locals: {item: item}
            - else
              %li.mypage__content__tab-content__item-list--none
                売却済みの商品はありません

    .mypage__side
      =render "shared/sidebar"

app/views/mypage/show_detail.html.haml
%main.mypage

  .mypage__container
    .mypage__contents
      .mypage__content__detail
        .mypage__content__head.mypage__content__head--image
          %section.mypage__content__head__user-icon
            = link_to mypage_show_path do
              %figure
                = image_tag @user.image.url, size: "180x180"
              %h2.mypage__content__head__user-icon__name.bold
                = @user.nickname
              .mypage__content__head__user-icon__number
                .mypage__content__head__user-icon__number--rate
                  評価
                  %span.bold
                    0
                .mypage__content__head__user-icon__number--display
                  出品数
                  %span.bold
                    10
                    
        .white
          .item-content__detail-table__face--detail
            .item-content__detail-table__face--good
              = fa_icon "smile-o", class: "good-icon"
              %span.item-content__detail-table__face__name
                10
            .item-content__detail-table__face--normal
              = fa_icon "meh-o", class: "normal-icon"
              %span.item-content__detail-table__face__name
                10
            .item-content__detail-table__face--bad
              = fa_icon "frown-o", class: "bad-icon"
              %span.item-content__detail-table__face__name
                10
          .maypage__detail__introduce
            = @user.introduce

          .item__social-media-box
            %ul.item__social-media-box__links
              %li
                =link_to "http://www.facebook.com" do
                  =fa_icon "facebook-square", class:"icon-facebook"
              %li
                =link_to "http://www.twitter.com" do
                  =fa_icon "twitter-square", class:"icon-twitter"
              %li
                =link_to "http://www.pinterest.com" do
                  =fa_icon "pinterest-square", class:"icon-pinterest"

          .item-other
            %section.item-other__user-items
              %h2.item-other__user-items__head
                = link_to "この出品者の商品", class: "link item-link"
              .item-other__user-items__content
                %section.item-other__user-items__content__box
                  = link_to class: "link item-link" do
                    %figure.item-other__user-items__content__box__photo
                      = image_tag("other-item.png", class: "item-image", size: "220x220")
                    .item-other__user-items__content__box__body
                      %h3.item-other__user-items__content__box__body__name
                        ケーキ
                      .item-other__user-items__content__box__num
                        .item-other__user-items__content__box__num__price
                          ¥ 20,000
                        .item-other__user-items__content__box__num__likes
                          =fa_icon "heart-o", class: "like-icon"
                          %span.item-other__user-items__content__box__num__likes__num
                          100
    .mypage__side
      =render "shared/sidebar"

app/views/mypage/sms_confirmation.html.haml
-breadcrumb :sms_confirmation
%main.mypage
  .mypage__container
    .mypage__content
      .single__page__main
        .single__page__main__container
          %h2.single__page__main__head
            完了
      .single__page__main
        .single__page__main__container
          .single__form.single__form--big
            .single__btn
              確認済みです
    .mypage__side
      =render "shared/sidebar"